Update new.py
Data:
                            open   high    low  close  volume  trade_count  \
timestamp                                                                    
2019-01-02 09:00:00+00:00  99.40  99.40  98.88  99.20     858           17   
2019-01-02 09:15:00+00:00  99.20  99.23  99.20  99.23     668            5   
2019-01-02 09:30:00+00:00  99.35  99.35  99.20  99.20    2644           21   
2019-01-02 10:00:00+00:00  99.49  99.90  99.49  99.88    3743           17   
2019-01-02 10:15:00+00:00  99.60  99.60  99.60  99.60     600            3   

                                vwap   returns  sma  ema  ...  middle_bb  \
timestamp                                                 ...              
2019-01-02 09:00:00+00:00  99.161072       NaN  NaN  NaN  ...        NaN   
2019-01-02 09:15:00+00:00  99.213773  0.000302  NaN  NaN  ...        NaN   
2019-01-02 09:30:00+00:00  99.246634 -0.000302  NaN  NaN  ...        NaN   
2019-01-02 10:00:00+00:00  99.757868  0.006855  NaN  NaN  ...        NaN   
2019-01-02 10:15:00+00:00  99.600333 -0.002803  NaN  NaN  ...        NaN   

                           lower_bb  rsi  stoch_k  stoch_d  macd  macd_signal  \
timestamp                                                                       
2019-01-02 09:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:30:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   

                           macd_histogram  adx  atr  
timestamp                                            
2019-01-02 09:00:00+00:00             NaN  0.0  0.0  
2019-01-02 09:15:00+00:00             NaN  0.0  0.0  
2019-01-02 09:30:00+00:00             NaN  0.0  0.0  
2019-01-02 10:00:00+00:00             NaN  0.0  0.0  
2019-01-02 10:15:00+00:00             NaN  0.0  0.0  

[5 rows x 21 columns]
Missing values in the data:
open               0
high               0
low                0
close              0
volume             0
trade_count        0
vwap               0
sma               13
ema               13
upper_bb          13
middle_bb         13
lower_bb          13
rsi               13
stoch_k           13
stoch_d           15
macd              25
macd_signal       33
macd_histogram    33
adx                0
atr                0
dtype: int64
Infinite values in the data:
open              0
high              0
low               0
close             0
volume            0
trade_count       0
vwap              0
sma               0
ema               0
upper_bb          0
middle_bb         0
lower_bb          0
rsi               0
stoch_k           0
stoch_d           0
macd              0
macd_signal       0
macd_histogram    0
adx               0
atr               0
dtype: int64

Preprocessed data:
X: [[9.43770323e-03 8.91018533e-03 7.48035412e-03 8.72219799e-03
  2.05508083e-05 1.14850945e-04 8.29013731e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [8.64461892e-03 8.23697133e-03 8.75360589e-03 8.84113706e-03
  1.53995503e-05 2.87127363e-05 8.49920468e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [9.23943215e-03 8.71218121e-03 8.75360589e-03 8.72219799e-03
  6.89726336e-05 1.43563681e-04 8.62956582e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [9.79459117e-03 1.08902265e-02 9.90749030e-03 1.14181501e-02
  9.87685945e-05 1.14850945e-04 1.06576553e-02 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [1.02307875e-02 9.70220181e-03 1.03451706e-02 1.03080522e-02
  1.35559421e-05 1.43563681e-05 1.00327065e-02 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]]
Y: [0 0 0 0 0]
Data:
                            open   high    low  close  volume  trade_count  \
timestamp                                                                    
2019-01-02 09:00:00+00:00  99.40  99.40  98.88  99.20     858           17   
2019-01-02 09:15:00+00:00  99.20  99.23  99.20  99.23     668            5   
2019-01-02 09:30:00+00:00  99.35  99.35  99.20  99.20    2644           21   
2019-01-02 10:00:00+00:00  99.49  99.90  99.49  99.88    3743           17   
2019-01-02 10:15:00+00:00  99.60  99.60  99.60  99.60     600            3   

                                vwap   returns  sma  ema  ...  middle_bb  \
timestamp                                                 ...              
2019-01-02 09:00:00+00:00  99.161072       NaN  NaN  NaN  ...        NaN   
2019-01-02 09:15:00+00:00  99.213773  0.000302  NaN  NaN  ...        NaN   
2019-01-02 09:30:00+00:00  99.246634 -0.000302  NaN  NaN  ...        NaN   
2019-01-02 10:00:00+00:00  99.757868  0.006855  NaN  NaN  ...        NaN   
2019-01-02 10:15:00+00:00  99.600333 -0.002803  NaN  NaN  ...        NaN   

                           lower_bb  rsi  stoch_k  stoch_d  macd  macd_signal  \
timestamp                                                                       
2019-01-02 09:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:30:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   

                           macd_histogram  adx  atr  
timestamp                                            
2019-01-02 09:00:00+00:00             NaN  0.0  0.0  
2019-01-02 09:15:00+00:00             NaN  0.0  0.0  
2019-01-02 09:30:00+00:00             NaN  0.0  0.0  
2019-01-02 10:00:00+00:00             NaN  0.0  0.0  
2019-01-02 10:15:00+00:00             NaN  0.0  0.0  

[5 rows x 21 columns]
Raw data:
                            open   high    low  close  volume  trade_count  \
timestamp                                                                    
2019-01-02 09:00:00+00:00  99.40  99.40  98.88  99.20     858           17   
2019-01-02 09:15:00+00:00  99.20  99.23  99.20  99.23     668            5   
2019-01-02 09:30:00+00:00  99.35  99.35  99.20  99.20    2644           21   
2019-01-02 10:00:00+00:00  99.49  99.90  99.49  99.88    3743           17   
2019-01-02 10:15:00+00:00  99.60  99.60  99.60  99.60     600            3   

                                vwap   returns  sma  ema  ...  middle_bb  \
timestamp                                                 ...              
2019-01-02 09:00:00+00:00  99.161072       NaN  NaN  NaN  ...        NaN   
2019-01-02 09:15:00+00:00  99.213773  0.000302  NaN  NaN  ...        NaN   
2019-01-02 09:30:00+00:00  99.246634 -0.000302  NaN  NaN  ...        NaN   
2019-01-02 10:00:00+00:00  99.757868  0.006855  NaN  NaN  ...        NaN   
2019-01-02 10:15:00+00:00  99.600333 -0.002803  NaN  NaN  ...        NaN   

                           lower_bb  rsi  stoch_k  stoch_d  macd  macd_signal  \
timestamp                                                                       
2019-01-02 09:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:30:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   

                           macd_histogram  adx  atr  
timestamp                                            
2019-01-02 09:00:00+00:00             NaN  0.0  0.0  
2019-01-02 09:15:00+00:00             NaN  0.0  0.0  
2019-01-02 09:30:00+00:00             NaN  0.0  0.0  
2019-01-02 10:00:00+00:00             NaN  0.0  0.0  
2019-01-02 10:15:00+00:00             NaN  0.0  0.0  

[5 rows x 21 columns]

Preprocessed data:
X: [[9.43770323e-03 8.91018533e-03 7.48035412e-03 8.72219799e-03
  2.05508083e-05 1.14850945e-04 8.29013731e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [8.64461892e-03 8.23697133e-03 8.75360589e-03 8.84113706e-03
  1.53995503e-05 2.87127363e-05 8.49920468e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [9.23943215e-03 8.71218121e-03 8.75360589e-03 8.72219799e-03
  6.89726336e-05 1.43563681e-04 8.62956582e-03 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [9.79459117e-03 1.08902265e-02 9.90749030e-03 1.14181501e-02
  9.87685945e-05 1.14850945e-04 1.06576553e-02 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]
 [1.02307875e-02 9.70220181e-03 1.03451706e-02 1.03080522e-02
  1.35559421e-05 1.43563681e-05 1.00327065e-02 8.13850541e-03
  8.00601312e-03 8.61286705e-03 8.13850541e-03 1.10762985e-02
  4.63906966e-01 3.72549020e-01 2.50108932e-01 5.67964681e-01
  5.50464955e-01 5.05781598e-01 0.00000000e+00 0.00000000e+00]]
Y: [0 0 0 0 0]
Original x shape: (61263, 20)
Model's input shape: (21,)
Current index:  0
Current index:  1
episode: 19/20, score: 0, e: 0.01
Data:
                            open   high    low  close  volume  trade_count  \
timestamp                                                                    
2019-01-02 09:00:00+00:00  99.40  99.40  98.88  99.20     858           17   
2019-01-02 09:15:00+00:00  99.20  99.23  99.20  99.23     668            5   
2019-01-02 09:30:00+00:00  99.35  99.35  99.20  99.20    2644           21   
2019-01-02 10:00:00+00:00  99.49  99.90  99.49  99.88    3743           17   
2019-01-02 10:15:00+00:00  99.60  99.60  99.60  99.60     600            3   

                                vwap   returns  sma  ema  ...  middle_bb  \
timestamp                                                 ...              
2019-01-02 09:00:00+00:00  99.161072       NaN  NaN  NaN  ...        NaN   
2019-01-02 09:15:00+00:00  99.213773  0.000302  NaN  NaN  ...        NaN   
2019-01-02 09:30:00+00:00  99.246634 -0.000302  NaN  NaN  ...        NaN   
2019-01-02 10:00:00+00:00  99.757868  0.006855  NaN  NaN  ...        NaN   
2019-01-02 10:15:00+00:00  99.600333 -0.002803  NaN  NaN  ...        NaN   

                           lower_bb  rsi  stoch_k  stoch_d  macd  macd_signal  \
timestamp                                                                       
2019-01-02 09:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 09:30:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:00:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   
2019-01-02 10:15:00+00:00       NaN  NaN      NaN      NaN   NaN          NaN   

                           macd_histogram  adx  atr  
timestamp                                            
2019-01-02 09:00:00+00:00             NaN  0.0  0.0  
2019-01-02 09:15:00+00:00             NaN  0.0  0.0  
2019-01-02 09:30:00+00:00             NaN  0.0  0.0  
2019-01-02 10:00:00+00:00             NaN  0.0  0.0  
2019-01-02 10:15:00+00:00             NaN  0.0  0.0  

[5 rows x 21 columns]

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-25-df37225a5bcc> in <cell line: 436>()
    435 
    436 if __name__ == '__main__':
--> 437     main()

2 frames

<ipython-input-25-df37225a5bcc> in main()
    427         state = np.concatenate(([test_env.shares, test_env.balance, test_env.equity], state))
    428         state = state.reshape((1, -1))
--> 429         action = np.argmax(model.predict(state)[0])
    430         state, reward, done, info = test_env.step(action)
    431 

/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

/usr/local/lib/python3.10/dist-packages/keras/engine/training.py in tf__predict_function(iterator)
     13                 try:
     14                     do_return = True
---> 15                     retval_ = ag__.converted_call(ag__.ld(step_function), (ag__.ld(self), ag__.ld(iterator)), None, fscope)
     16                 except:
     17                     do_return = False

ValueError: in user code:

    File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 2169, in predict_function  *
        return step_function(self, iterator)
    File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 2155, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 2143, in run_step  **
        outputs = model.predict_step(data)
    File "/usr/local/lib/python3.10/dist-packages/keras/engine/training.py", line 2111, in predict_step
        return self(x, training=False)
    File "/usr/local/lib/python3.10/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "/usr/local/lib/python3.10/dist-packages/keras/engine/input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 60, 24), found shape=(None, 27)